#!/usr/bin/env bash

# inspired by https://github.com/necolas/dotfiles

set -e
set -u


full=false
update=false
help=false

# idiomatic parameter and option handling in sh
while test $# -gt 0
do
    case "$1" in
        -h|--help|help) help=true;
            echo "Dotfiles installation script"
            echo "\tOptional args:"
            echo "\thelp   ... display this messge"
            echo "\tfull   ... install software"
            echo "\tupdate ... re-download from github"
            ;;
        full) full=true
            ;;
        update) update=true
            ;;
        *) echo "argument $1"
            ;;
    esac
    shift
done

# exit if we're printing help
if [ "$help" = true ]; then
    exit 0
fi


DOTFILES_DIRECTORY="${HOME}/.dotfiles"
DOTFILES_TARBALL_PATH="https://github.com/stklik/dotfiles/tarball/master"

# ----------------------------------
# Download dotfiles
# ----------------------------------

# if update was passed, then we delete the current dotfiles directory and re-download it
if [ "$update" = true ]; then
    echo "'update' option selected. Deleting dotfiles directory: ${DOTFILES_DIRECTORY}"
    if [ -d ${DOTFILES_DIRECTORY} ]; then
        \rm -rf ${DOTFILES_DIRECTORY};
    fi
fi

# If missing, download and extract the dotfiles repository
if [ ! -d ${DOTFILES_DIRECTORY} ]; then
    # check if curl exists, try installing if not
    if [ ! $(command -v curl) ]; then
        if [ $(command -v apt) ]; then
            echo "Didn't find cURL, but we need it. Installing it now!"
            sudo apt install -v curl;
        elif [ $(command -v brew) ]; then
            echo "Didn't find cURL, but we need it. Installing it now!"
            brew install curl 2>/dev/null;
        else
            echo "Failed to download dotfiles!"
            echo "cURL not installed, but I don't know how to install it...";
            echo "Install it please, so I can proceed!";
            exit 1;
        fi
    fi

    printf "Downloading dotfiles...\033[m\n"
    mkdir ${DOTFILES_DIRECTORY}
    # Get the tarball
    curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOTFILES_TARBALL_PATH}
    # Extract to the dotfiles directory
    tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOTFILES_DIRECTORY}
    # Remove the tarball
    rm -rf ${HOME}/dotfiles.tar.gz
fi

cd ${DOTFILES_DIRECTORY}

# ----------------------------------
# Software Installation with arg 'full' (optional)
# ----------------------------------

# check if we're bootstrapping
# then we need to install everything
if [ "$full" = true ]; then
    if [ "$(uname)" = "Darwin" ]; then
        echo "Triggering full Mac bootstrapping...";
        sh ${DOTFILES_DIRECTORY}/bootstrap.mac.sh
    elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
        echo "Triggering full Linux bootstrapping...";
        sh ${DOTFILES_DIRECTORY}/bootstrap.linux.sh
    fi
else
    echo "INFO: Didn't see argument 'full'. Not installing any software. Config only.";
fi


# ----------------------------------
echo "Copying actual dotfiles & folders"
# ----------------------------------

timestamp=`date +%Y-%m-%d_%H-%M-%S`
DOTFILES_BACKUP="${HOME}/.dotfiles-backup_$timestamp"

echo "Dotfiles Backup Folder is ${DOTFILES_BACKUP}"
mkdir -p ${DOTFILES_BACKUP};
for file in .{aliases,bash_profile,bashrc,exports,extra,functions,gitconfig,gitignore,latexmkrc,path,vimrc,zshrc}; do
    # if the file exists, back it up
    [ -r "${HOME}/$file" ] && [ -f "${HOME}/$file" ] && mv ${HOME}/$file ${DOTFILES_BACKUP};
    # now copy the one from here to home
	[ -r "$file" ] && [ -f "$file" ] && ln -s ${DOTFILES_DIRECTORY}/$file ${HOME}/$file && echo "linked ~/$file to $DOTFILES_DIRECTORY/$file";
done;
unset file;

# copy folders (same as above, not really sure why I'm duplicating...)
# for dir in .{vim}; do
    # if the file exists, back it up
dir=".vim"
[ -r "${HOME}/$dir" ] && [ -d "${HOME}/$dir" ] && mv ${HOME}/$dir ${DOTFILES_BACKUP};
# now copy the one from here to home
[ -r "$dir" ] && [ -d "$dir" ] && ln -s ${DOTFILES_DIRECTORY}/$dir ${HOME}/$dir && echo "linked ~/$dir to $DOTFILES_DIRECTORY/$dir";
# done;
unset dir;

# now install the vim plugins
vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty

# create a .hushlogin
touch ${HOME}/.hushlogin

# make new settings available
source ${HOME}/.bash_profile
